version: "3.3"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    restart: always
    container_name: api
    volumes:
      - ./api:/app/api
      - ./wsgi.py:/app/wsgi.py
      - ./bin:/app/bin
volumes:
  app: